# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Style build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  page:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.2.8
      with:
        source: style.sass
        destination: dist/style.css
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: . # The folder the action should deploy.